### ISSUE TITLE
DcRonan/Youtube-Peer to peer programming

### ISSUE THREAD

**Issue by AkintoyeOlamide** [DcRonan/YouTube#2]
1. The styling had so much ID's- The presenter should use more of classes
2. The HTML had so much inline styling which makes the HTML bulky.
3. Too much use of floats disturbs the CSS so its recommended to use flexboxes or CSS grid.
4.  Menu Icon wasn't available, but it wasn't a requirement.
5.  It was discovered for the iframe video it's not necessary to use the frame border the way it was used by youtube.

**Comment by LamiaSristy** [comment]
4 of the 5 issues are about CSS, and we are working on it.
Also, we are working on a clean code.
For no. 4, we will add the menu icon.
Thanks a lot for suggesting the changes.
